server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-service:8761/eureka

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://keycloak:8080/realms/sbm-realm
  zipkin:
    base-url: http://zipkin:9411

  r2dbc:
    url: r2dbc:postgresql://postgres-gateway:5433/postgres
    username: admin
    password: 1111

  redis:
    host: redis
    port: 6379
    client-type: lettuce

  autoconfigure:
    exclude: org.springframework.cloud.gateway.config.GatewayRedisAutoConfiguration

  cloud:
    gateway:
      filter:
        request-rate-limiter:
          deny-empty-key: false
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - name: Path
              args:
                patterns: /api/product

        - id: order-service
          uri: lb://order-service
          predicates:
            - name: Path
              args:
                patterns: "/api/order"
          filters:
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@apiRateLimiter}"
                key-resolver: "#{@apiRateLimiterKeyResolver}"

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - name: Path
              args:
                patterns: /api/inventory

        - id: discover-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discover-service-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        - id: get_route
          uri: http://httpbin.org/
          predicates:
            - name: Path
              args:
                patterns: /get
            - name: Method
              args:
                methods: GET
          filters:
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@apiRateLimiter}"
                key-resolver: "#{@apiRateLimiterKeyResolver}"

        - id: flask-service
          uri: http://flask-service:5000
          predicates:
            - name: Path
              args:
                patterns: /api/flask/hello
